---
name: Build Windows
on: [push, pull_request]
env:
  PATH_SOURCE: src
  PATH_BUILD: build
  BUILD_CONFIG: Release
jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          path: ~/.nuget/packages
          restore-keys: ${{ runner.os }}-nuget
      - name: Build Version
        shell: bash
        run: |
          dotnet tool install --global minver-cli --version 5.0.0
          echo "MINVERVERSIONOVERRIDE=$(minver --tag-prefix v)" >> ${GITHUB_ENV}
      - name: Build
        run: make build
        working-directory: ${{ env.PATH_SOURCE }}
      - name: Test
        run: make test
        working-directory: ${{ env.PATH_SOURCE }}
      - name: Upload job artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.PATH_SOURCE }}/${{ env.PATH_BUILD }}/*
